language: node_js
node_js:
  - "10"

install:
  - npm run postinstall

script:
  - cd ./client/ && npm run build

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME
  on: 
    branch: master

